### ISSUE TITLE
TVDB Legacy API Key Deprecation, (Issue listing titles)

### ISSUE THREAD

**Issue by JuezFenix** [kariudo/animetarr#1]
When i try to open the webui i dont show nothing and this appears in log:

```
   ...
Failed to match (a translation alias probably needs to be added to the TVDB):  I've Been Killing Slimes for 300 Years and Maxed Out My Level SPRING 2021
Error: Name cannot be shortened.
    at retryWithShorterName (/app/index.js:328:13366)
    at matchSeriesTitle (/app/index.js:328:13155)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/index.js:328:4350
    at async Promise.all (index 15)
    at async /app/index.js:328:4303
Failed to match (a translation alias probably needs to be added to the TVDB):  Higehiro: After Being Rejected, I Shaved and Took in a High School Runaway SPRING 2021
Error: Name cannot be shortened.
    at retryWithShorterName (/app/index.js:328:13366)
    at matchSeriesTitle (/app/index.js:328:13155)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/index.js:328:4350
    at async Promise.all (index 18)
    at async /app/index.js:328:4303
Failed to match (a translation alias probably needs to be added to the TVDB):  Full Dive: This Ultimate Next-Gen Full Dive RPG Is Even Shittier than Real Life! SPRING 2021
```

**Comment by kariudo** [comment]
Did you configure the required environment variables for your API keys? I know for sure all of those series match correctly (since I have all of them tracked).

**Comment by kariudo** [comment]
It won't be able to obtain TVDB data without the key if you haven't obtained one and configured it: https://www.thetvdb.com/api-information

See the `README.md`. Let me know if you're still stuck after setting all of that up.

**Comment by JuezFenix** [comment]
Do you refer to - e TVDB_API_KEY "v4 tvdb api key"? Supose i have configured.

**Comment by kariudo** [comment]
I see what happened here, sorry I haven't had a chance to circle back. Up until the last week or so they seem to have continued supporting their "Legacy" API keys (which I have had in my configs since it predated their v4 model). 

It would appear that their new model requires a subscription per user to access API data now if you aren't a company negotiating a fee. I'm not terribly keen on requiring myself or users of this tool to cough up an annual subscription to get the required PIN that must be used with an API key now. 

I will follow up here on this issue, and either change out the backend to use another means of getting the TVDB ID queries completed or at least add support for their now paid API access if I can't find a good alternative.

**Comment by kariudo** [comment]
I have opened a ticket with TheTVDB to investigate options on that end.
